Add panic placeholders for new float support added to Cryptol.
GaloisInc/cryptol-verifier pull request #22
Opened 2020-06-30 05:41 UTC by kquick

This does not provide proper handling of the new float types, but adds panic calls on pattern matches to re-enable successful compilation and establish placeholders for future support.

2020-06-30 15:23 UTC, yav requested changes
The panics look fine, but I think we should change how we look up primitives.

2020-07-01 15:33 UTC, yav requested changes
We should definitely fix the names of the `Array` primitives as that will break Andre's code.

On the stylistic issue, it's up to you.

2020-07-01 15:33 UTC, yav commented on src/Verifier/SAW/Cryptol.hs
> +
This is just stylistic, but I'd
  1. add separate top-level declaration for the map of translations (e.g. `allPrims = prelPrims <> floatPrims <> arrayPrim`)
  2. I'd reduce the guards to 2 as that matches the logic more directly: either the name is a primitve or not.  In the case for the primitive I'd use a `case` to lookup in `allPrims` and `panic` if the primitive is missing.

2020-07-01 15:33 UTC, yav commented on src/Verifier/SAW/Cryptol.hs
> +   ])
This is incorrect.  The `Array` primitives are in their own module, so we should make a separate map for them.  Their names are of the form `PrimIdent arrayName x`.  In general, there shouldn't be any `::` in the names of primitives.

By the way, I just noticed that we don't seem to have a convenience short-cut for the `Array` module (i.e., `arrayPrim = PrimIdent arrayName`), so feel free to add it to `Crytpol.Util.Ident`.  I am fine if you just add it without a pull request, but whatever works for you.

2020-07-02 07:48 UTC, brianhuffman commented
Superseded by #26.

2020-07-02 07:48 UTC, closed without merging

2020-07-02 17:29 UTC, kquick commented
Sorry @brianhuffman , looks like I had forgotten to push my latest patch set (I had run into the RecordSet changes in verifying those) and you had to redo that set of changes.  Thanks for resolving this in #26.